In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_excel("../data/fraud_dataset.xlsx")

In [67]:
df.head()

,Transaction_ID,Customer_ID,Age,Gender,Product_Category,Amount,Payment_Method,Device,Browser,Country,IP_Address,Transaction_Time,Shipping_Address_Match,Is_Fraud
0,T000001,C00785,42,Male,Books,28633.39,COD,Tablet,Edge,Singapore,102.248.8.136,2025-01-13 23:34:00,No,0
1,T000002,C00981,46,Female,Electronics,15707.87,COD,Desktop,Chrome,Canada,202.139.23.128,2025-07-26 11:12:00,Yes,0
2,T000003,C02554,22,Male,Groceries,29847.79,Credit Card,Mobile,Chrome,Canada,5.63.106.60,2025-06-19 04:46:00,Yes,0
3,T000004,C00197,69,Male,Sports,6357.38,UPI,Tablet,Chrome,Canada,9.239.83.9,2025-05-08 12:09:00,No,1
4,T000005,C00082,37,Female,Electronics,44753.01,Net Banking,Mobile,Chrome,UK,160.87.49.112,2025-11-27 14:29:00,No,0

In [68]:
df.tail()

,Transaction_ID,Customer_ID,Age,Gender,Product_Category,Amount,Payment_Method,Device,Browser,Country,IP_Address,Transaction_Time,Shipping_Address_Match,Is_Fraud
9995,T009996,C02440,19,Male,Groceries,10054.23,UPI,Tablet,Firefox,Singapore,94.100.88.168,2025-05-04 00:22:00,Yes,0
9996,T009997,C01191,32,Female,Electronics,4942.84,UPI,Mobile,Firefox,Germany,106.142.248.222,2025-12-27 01:36:00,No,0
9997,T009998,C01529,56,Male,Fashion,32970.73,COD,Tablet,Firefox,Germany,151.186.106.105,2025-03-23 12:42:00,Yes,0
9998,T009999,C01642,30,Female,Home,18438.96,COD,Mobile,Edge,Germany,89.92.161.198,2025-06-13 11:14:00,No,0
9999,T010000,C01792,42,Male,Electronics,48809.60,Credit Card,Mobile,Chrome,Germany,184.49.122.35,2025-06-07 20:21:00,No,0

In [69]:
df.shape

(10000, 14)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction_ID          10000 non-null  str
 1   Customer_ID             10000 non-null  str
 2   Age                     10000 non-null  int64
 3   Gender                  10000 non-null  str
 4   Product_Category        10000 non-null  str
 5   Amount                  10000 non-null  float64
 6   Payment_Method          10000 non-null  str
 7   Device                  10000 non-null  str
 8   Browser                 10000 non-null  str
 9   Country                 10000 non-null  str
 10  IP_Address              10000 non-null  str
 11  Transaction_Time        10000 non-null  str
 12  Shipping_Address_Match  10000 non-null  str
 13  Is_Fraud                10000 non-null  int64
dtypes: float64(1), int64(2), str(11)
memory usage: 1.1 MB

In [71]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Age', 'Gender', 'Product_Category',
       'Amount', 'Payment_Method', 'Device', 'Browser', 'Country',
       'IP_Address', 'Transaction_Time', 'Shipping_Address_Match', 'Is_Fraud'],
      dtype='str')

In [72]:
df.isnull().sum()

Transaction_ID            0
Customer_ID               0
Age                       0
Gender                    0
Product_Category          0
Amount                    0
Payment_Method            0
Device                    0
Browser                   0
Country                   0
IP_Address                0
Transaction_Time          0
Shipping_Address_Match    0
Is_Fraud                  0
dtype: int64

In [73]:
df.duplicated().sum()

np.int64(0)